version: '3.1'
volumes:
    mongo_data:
services:
  plarintest:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./plarintest:/PlarinTest
    ports:
      - "8000:8000"
    depends_on:
        - mongo
  mongo:
    image: mongo
    restart: always
    volumes:
        - /Users/egor/data:/data/db
    ports:
      - "27017:27017"